### ISSUE TITLE
能有个完整的demo吗

### ISSUE THREAD

**Issue by YinRenjie1993** [wubostc/virtualized-table-for-antd#1]
我试了下 就渲染了第一行

**Comment by wubostc** [comment]
Hello @YinRenjie1993 . Please provide a online reproduction by forking this link https://codesandbox.io/s/m7j063zy89

**Comment by wubostc** [comment]
@YinRenjie1993  , it was fixed in v0.0.4

**Comment by YinRenjie1993** [comment]
@wubostc 加了scroll果然好了，还有个问题0.0.5就是第一次加载会只有一条数据渲染，在	componentDidMount加了句this.scrollHook({ target: { scrollTop: 0, scrollLeft: 0 } });解决了
