### ISSUE TITLE
有计划支持树形结构的数据么

### ISSUE THREAD

**Issue by sj279811799** [wubostc/virtualized-table-for-antd#11]
目前如果数据是树形结构，渲染出来的是有问题的，有计划对树形结构进行支持么。
![image](https://user-images.githubusercontent.com/12233760/62751870-eb2e0300-ba97-11e9-96fb-1ac229eaf975.png)

**Comment by wubostc** [comment]
今天我看下怎么解决吧。

**Comment by wubostc** [comment]
@sj279811799 树形结构会丢失上下文，需要重新设计代码，暂时先回避树形结构吧。

**Comment by sj279811799** [comment]
我这边暂时先设置树形结构全部展开，不可收起。

**Comment by jsonshao** [comment]
合并行好像不支持呢

**Comment by wubostc** [comment]
> 合并行好像不支持呢

什么合并行？

**Comment by jsonshao** [comment]
> > 合并行好像不支持呢
> 
> 什么合并行？

就是像antd的行合并啊时了下会错位

**Comment by jsonshao** [comment]
表格的check box好像也不能用呢，点 了全选没反应

**Comment by jsonshao** [comment]
表格切换，或者路由切换重新进来表格高度变成0了不渲染数据，这很尴尬

**Comment by jsonshao** [comment]
能否将你包里antd的版本升级最新，我项目打包了2份antd，静态资源有点大

**Comment by wubostc** [comment]
> 
> 
> 能否将你包里antd的版本升级最新，我项目打包了2份antd，静态资源有点大

请不要把问题反馈在这个无关issue下

**Comment by chunmu** [comment]
hello  树形数据解决了吗

**Comment by wubostc** [comment]
> 

解决了
