### ISSUE TITLE
是每次滚动都会添加元素吗

### ISSUE THREAD

**Issue by jiandandkl** [wubostc/virtualized-table-for-antd#110]
version: 0.7.9
看了下dom，发现每次滚动都会添加元素进入table，造成卡顿的现象，是不是应该快触底的时候再加载下一批？
还是我的使用姿势不对呢？

```javascript
components={VTComponents({
  id: VTTableId,
  // debug: true,
  overscanRowCount: 20,
  onScroll: ({ left, top }) => {
    console.log(2324, top);
    VTCtx.top = top;
  }
})}
```
发现也不是每次，第一批虚拟的dom出现之前并没有每次加载，之后再滚动就是每次都加载新的元素了

**Comment by jiandandkl** [comment]
> version: 0.7.9 看了下dom，发现每次滚动都会添加元素进入table，造成卡顿的现象，是不是应该快触底的时候再加载下一批？ 还是我的使用姿势不对呢？尝试打印onScroll的日志，发现并没有调用
> 
> ```js
> components={VTComponents({
>   id: VTTableId,
>   // debug: true,
>   overscanRowCount: 20,
>   onScoll: ({ left, top }) => {
>     console.log(2324, top);
>     return (VTCtx.top = top);
>   }
> })}
> ```

**Comment by wubostc** [comment]
你换成最新版本试试
