### ISSUE TITLE
vt_opts scroll and y not typed correctly

### ISSUE THREAD

**Issue by Stainless2k** [wubostc/virtualized-table-for-antd#116]
right [here](https://github.com/wubostc/virtualized-table-for-antd/blob/27ec8c2af525d63e6faa00d0a9f34ff4820970bc/src/vt.tsx#L62) scroll is typed wrongly, imo it should not  be optional since omitting the scroll option just leads to errors. 

e.g `  const [vt] = useVT(() => ({}), []);` doing this wont cause any warnings in your IDE but will lead to this error ->
`Cannot read properties of undefined (reading 'y')`

Also `y` is typed as just number but as seen [here](https://github.com/wubostc/virtualized-table-for-antd/blob/27ec8c2af525d63e6faa00d0a9f34ff4820970bc/src/vt.tsx#L271) is intended to be also be string.
e.g `  const [vt] = useVT(() => ({ scroll: { y: '100%' } }), []);` this will lead to typescript errors because `y` i just typed as number

it should be typed like this
```
  scroll: {
    y: number | string;
  };
```

**Comment by wubostc** [comment]
ok

**Comment by wubostc** [comment]
solved in 1.1.5
![06F818B2](https://user-images.githubusercontent.com/11424697/161018999-063c15a6-4b10-440a-a38a-042096108c7a.png)
