### ISSUE TITLE
自定义{header: {cell:  ... } }无效

### ISSUE THREAD

**Issue by ilostidea** [wubostc/virtualized-table-for-antd#117]
你好。
set_components({
            {
                body: {
                    row: EditableRow,
                    cell: EditableCell,
                }
            } ,
            {
                header: {
                    cell: ResizableTitle
                },
            }
     })

自定义的header没生效，貌似使用了默认的header。

**Comment by wubostc** [comment]
我看看

**Comment by wubostc** [comment]
语法不对，看得很累，你自己检查

**Comment by wubostc** [comment]
复现不了，我关了
