### ISSUE TITLE
this doesn't work on nextjs

### ISSUE THREAD

**Issue by thanglong134** [wubostc/virtualized-table-for-antd#12]
Throwing an error: "ReferenceError: window is not defined"

how to solve this problem?

**Comment by wubostc** [comment]
You can try to change lines 222 to 223, as follows.(the `window` is just for test.)

```js
if (window) {
    const p: any = window;
    p["&REACT_DEBUG"] && p[`&REACT_HOOKS${p["&REACT_DEBUG"]}`][15] && (this.VTWrapperRender = (...args) => <tbody {...args[3]}>{args[2]}</tbody>);
}
```

if everything is works well, you can PR.

**Comment by wubostc** [comment]
Hello @thanglong134, I commited [55385d6](https://github.com/wubostc/virtualized-table-for-antd/commit/55385d61155729effa0ff292887ca7b954600d56) just now.

I will publish it on npm in a few days.

**Comment by thanglong134** [comment]
thank you, i'm looking forward version updated on npm soon

**Comment by wubostc** [comment]
[v0.5.5](https://www.npmjs.com/package/virtualizedtableforantd/v/0.5.5)  has been released!
