### ISSUE TITLE
当deps中依赖的scoll.y发生变化后，RAF_update_self函数没有重新执行，导致scoll.y的值一直是0

### ISSUE THREAD

**Issue by xian107** [wubostc/virtualized-table-for-antd#122]
![image](https://user-images.githubusercontent.com/13252682/187134551-de4e9143-2bc7-4c30-9890-133056ec69e1.png)

![image](https://user-images.githubusercontent.com/13252682/187121023-e9d23156-66e0-4bd9-a73b-2342e71cd17d.png)

![image](https://user-images.githubusercontent.com/13252682/187134068-c5f8b359-38de-4547-b622-0c64d46b970d.png)

**Comment by wubostc** [comment]
来个复现事例

**Comment by xian107** [comment]
> 来个复现事例
@wubostc 大神这是示例
https://codesandbox.io/s/nostalgic-water-m6x38j?file=/src/App.js

![image](https://user-images.githubusercontent.com/13252682/188563802-9544589c-f127-4ada-a94e-4a5f4ebf1051.png)

**Comment by xian107** [comment]
大神这是示例，望请指点
https://codesandbox.io/s/nostalgic-water-m6x38j?file=/src/App.js




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wubostc/virtualized-table-for-antd"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月31日(星期三) 晚上7:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wubostc/virtualized-table-for-antd] 当deps中依赖的scoll.y发生变化后，RAF_update_self函数没有重新执行，导致scoll.y的值一直是0 (Issue #122)





 
来个复现事例

**Comment by wubostc** [comment]
额，其实你可以用第三个返回值ref.current来做。
https://codesandbox.io/s/broken-grass-wxjdo2?file=/src/App.js

```js
refVt.current.scrollTo(1);
```

**Comment by wubostc** [comment]
@xian107
