### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by FreeFrags** [wubostc/virtualized-table-for-antd#123]
Could you please add support for React 18? 

The peer dependencies include ^16.8.0 || ^17.0.0 

https://github.com/wubostc/virtualized-table-for-antd/blob/66f0e80c6a82e70b25574c36c4b6b39e3f81b73f/package.json#L57
https://github.com/wubostc/virtualized-table-for-antd/blob/66f0e80c6a82e70b25574c36c4b6b39e3f81b73f/package.json#L58

**Comment by wubostc** [comment]
It will soon be ……

**Comment by wubostc** [comment]
published
