### ISSUE TITLE
当用点击事件改变table数据时，列表超过5个项，却只出来5个

### ISSUE THREAD

**Issue by xian107** [wubostc/virtualized-table-for-antd#126]
@wubostc 请教大神一个问题
示例代码：https://codesandbox.io/s/autumn-leftpad-1df31x?file=/src/App.js
![image](https://user-images.githubusercontent.com/13252682/191943267-f8a61317-3103-4c3b-9fbe-49ee8c5be1f1.png)

**Comment by xian107** [comment]
@wubostc 麻烦看看，这个如何解决？万分感激！

**Comment by wubostc** [comment]
你可以先把 '700px' 改成 700

**Comment by xian107** [comment]
> 你可以先把 '700px' 改成 700
其实项目中一般都是用`calc(100vh - ${top})`，没有固定一个数值

**Comment by xian107** [comment]
> 你可以先把 '700px' 改成 700

@wubostc 其实项目中一般都是用calc(100vh - ${top})，没有固定一个数值
