### ISSUE TITLE
Responsive scroll "X" doesn't work as antd table

### ISSUE THREAD

**Issue by joseAAlexandre** [wubostc/virtualized-table-for-antd#129]
Is there a way to make X responsive with column information? The method used by the antd table is not working.

```scroll={{ y: 100, x: "max-content", whiteSpace: "nowrap" }}```

https://codesandbox.io/s/antd-reproduction-template-forked-7dql75?file=/index.js

**Comment by wubostc** [comment]
Is that what you want @joseAAlexandre 

https://codesandbox.io/s/antd-reproduction-template-forked-4bgs8j?file=/index.js

**Comment by joseAAlexandre** [comment]
It's working, but the column headers are fixed.

**Comment by joseAAlexandre** [comment]
This way works perfectly!!

```
const [vt, setComponent] = useVT(() => ({ scroll: { y: props.scroll.y, } }), []);

setComponent({
  table: ({ style, ...props }) => <table {...props}
    style={{ ...style, width: 'max-content' }}
  />
});

return (
  <Table components={vt}
    {...props} />
);
```
