### ISSUE TITLE
maxHeight 有时会计算错误

### ISSUE THREAD

**Issue by xian107** [wubostc/virtualized-table-for-antd#134]
@wubostc 当我搜索某条件的时候，再去切换tab菜单，会出现maxHeight计算不准的情况，示例没法复现，没找到规律，但是我有console.log出来关键数据，烦请看下
![image](https://user-images.githubusercontent.com/13252682/210498049-43b873f5-5f51-4fe8-83ca-fb386203fbd4.png)
![image](https://user-images.githubusercontent.com/13252682/210498785-a4360ac5-377f-48d0-9263-4a076e55baf5.png)
![image](https://user-images.githubusercontent.com/13252682/210498858-9ac11f04-4bae-4e1a-829a-6577c4edb252.png)

**Comment by xian107** [comment]
@wubostc 请问大神，这个该如何解决呢？

**Comment by wubostc** [comment]
晚上再看👀

**Comment by zyt0707** [comment]
@wubostc 您好！我也碰到这个问题，请问该怎么处理？

**Comment by wubostc** [comment]
> @wubostc 您好！我也碰到这个问题，请问该怎么处理？

最新分支修复了，本周更新一版

**Comment by wubostc** [comment]
发布了
