### ISSUE TITLE
树形展开的时候，如果行数增加，高度计算有问题

### ISSUE THREAD

**Issue by biaoqiu** [wubostc/virtualized-table-for-antd#136]
demo：https://codesandbox.io/s/xenodochial-leaf-30qp0b?file=/src/App.js

操作步骤：

1. 先展开两行数据
![image](https://user-images.githubusercontent.com/109496643/215987205-085f3926-32e1-4760-9ac9-13b994d75f02.png)

2. 然后切换到3行数据，此时自动收起
3. 展开三行数据，会出现滚动条
![image](https://user-images.githubusercontent.com/109496643/215987889-1cc7df1a-6f16-477a-9f36-25a7aba71da2.png)

**Comment by wubostc** [comment]
版本多少

**Comment by biaoqiu** [comment]
1.2.1，试了一下最新版1.2.2，也有这个问题
