### ISSUE TITLE
Table渲染问题

### ISSUE THREAD

**Issue by andyyxw** [wubostc/virtualized-table-for-antd#14]
组件首次加载是正常的，但是刷新组件后，表格数据就渲染不出来了。如下图：

![Snipaste_2019-10-29_10-53-24](https://user-images.githubusercontent.com/41931722/67735122-20feda00-fa3e-11e9-89ba-b8145474dcec.png)
![GIF](https://user-images.githubusercontent.com/41931722/67735124-24926100-fa3e-11e9-899a-7de59a646020.gif)

我找不到问题在哪，用的是最简单的用法，不确定是不是由于render多次导致的，但是后面几次render数据是传进来了的。
请帮忙分析一下可能是哪里出问题了，感谢。

**Comment by wubostc** [comment]
请尝试一下方法：
- 禁用Table.components属性后问题是否依旧？
- 更新到最新版本。
- 设置destory属性为true。
- VTComponents的id是否唯一？

无法解决，请发送debug日志，设置debug属性为true即可，之后拷贝控制台的输出。

**Comment by wubostc** [comment]
远程帮你看一下？

**Comment by wubostc** [comment]
> 
> 
>     * 禁用`Table.components`属性后正常。
> 
>     * `antd`和`virtualizedtableforantd` 均是最新版，尝试回退antd的版本至3.13.6，结果一样。
> 
>     * `destory`属性设置为true后重复上面的操作，二次刷新的时候出现报错，如图：
>       ![GIF](https://user-images.githubusercontent.com/41931722/67834781-41549480-fb23-11e9-9059-c8cc2e69bdb0.gif)
> 
>     * `VTComponents`的id是唯一的，只有这一个组件用了。
> 
>     * 设置了`debug`属性为true，但是控制台没有任何输出。。
>       ![20191030](https://user-images.githubusercontent.com/41931722/67834890-8ed10180-fb23-11e9-8acb-b29a107d652d.png)

加我qq，我帮你远程看看

**Comment by andyyxw** [comment]
> 加我qq，我帮你远程看看
1779391833，谢谢！

**Comment by qindj** [comment]
碰到同样的问题，请问是如何解决的？

**Comment by wubostc** [comment]
> 碰到同样的问题，请问是如何解决的？
> 
> yarn start，开发过程中，直接刷新页面，也会出现一次有，一次无的问题

你更新了最新版本了吗

**Comment by qindj** [comment]
> > 碰到同样的问题，请问是如何解决的？
> > yarn start，开发过程中，直接刷新页面，也会出现一次有，一次无的问题
> 
> 你更新了最新版本了吗

0.6.3 增加overscanRowCount 到50， 加了destroy之后，正常了

**Comment by wubostc** [comment]
> 
> 
> > > 碰到同样的问题，请问是如何解决的？
> > > yarn start，开发过程中，直接刷新页面，也会出现一次有，一次无的问题
> > 
> > 
> > 你更新了最新版本了吗
> 
> 0.6.3 增加overscanRowCount 到50， 加了destroy之后，正常了

我是说你用默认参数还会有这问题吗，那个调到50没什么用啊

**Comment by wubostc** [comment]
overscanRowCount 设成50很夸张了，会影响性能的

**Comment by qindj** [comment]
> > > > 碰到同样的问题，请问是如何解决的？
> > > > yarn start，开发过程中，直接刷新页面，也会出现一次有，一次无的问题
> > > 
> > > 
> > > 你更新了最新版本了吗
> > 
> > 
> > 0.6.3 增加overscanRowCount 到50， 加了destroy之后，正常了
> 
> 我是说你用默认参数还会有这问题吗，那个调到50没什么用啊

是，默认参数（只传id）,会有问题，随手加了overscanRowCount 和destroy之后，正常了

**Comment by qindj** [comment]
> overscanRowCount 设成50很夸张了，会影响性能的

多谢提醒，改成10了，的确快很多
