### ISSUE TITLE
isEnd not always true

### ISSUE THREAD

**Issue by Kestutis** [wubostc/virtualized-table-for-antd#141]
I have cases when `onScroll: async ({ isEnd, top }) => {` `isEnd` here is false, but there is no more space to scroll.
If I use trackpad and scroll with inertia I can push through this threshold to get `isEnd === true`. 
From debugging code I can see that `end: target.scrollHeight - target.clientHeight === Math.round(top),` can be off just by 1px sometimes. 

is there a way to set offset somehow? So can i fetch next page on infinity scroll a little bit earlier than table reached end? Also this would fix my problems when isEnd not always true, while there is no more place to scroll.

Ideally `onScroll` callback can expose simulated event or at least simulated event target and allow to do calculations myself. 
If this something you consider, I can create PR myself.

**Comment by matepaiva** [comment]
having the same problem here, i touch the end and it says `isEnd === false` :(

**Comment by giorgiveego** [comment]
Same for me

**Comment by Kestutis** [comment]
@wubostc when we can expect new release?
