### ISSUE TITLE
unessesary console.log()

### ISSUE THREAD

**Issue by Stainless2k** [wubostc/virtualized-table-for-antd#144]
with the newest version a console.log got added, please remove it

see [here](https://github.com/wubostc/virtualized-table-for-antd/blob/103e9fa2f5fde1163d6e149f0e79c53c22a9d483/src/index.tsx#L79)

**Comment by Kestutis** [comment]
Removed with https://github.com/wubostc/virtualized-table-for-antd/pull/145

**Comment by wubostc** [comment]
resolved in 1.3.1
