### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by Taymindis** [wubostc/virtualized-table-for-antd#16]
:19006/static/js/bundle.js:248771 Uncaught TypeError: Cannot read property 'style' of null
    at update_wrap_style (:19006/static/js/bundle.js:248771)
    at VTRow.collect_h_tr (:19006/static/js/bundle.js:248873)
    at VTRow.componentDidUpdate (:19006/static/js/bundle.js:248834)

不知為何， 當我transfer column的時候， 這問題就發生了， 原來的 antd table 是沒這問題的

![image](https://user-images.githubusercontent.com/14217761/68079869-b974d000-fe2b-11e9-80f3-4536d3030bb6.png)

**Comment by wubostc** [comment]
Thanks, @Taymindis !
你能把问题复现在codesandbox上吗？

**Comment by Taymindis** [comment]
hi Wubostc, 

當我放destroy:true 的時候， 問題就消失了， 也許是你的cache的問題，Table 不能修改 column

**Comment by wubostc** [comment]
0.6.2还会发生这类问题吗？

**Comment by Taymindis** [comment]
好像沒有了， 而且你的快滾也優化了。好！
