### ISSUE TITLE
固定左侧列后, 表格列出现空白

### ISSUE THREAD

**Issue by LBC100** [wubostc/virtualized-table-for-antd#17]
![image](https://user-images.githubusercontent.com/38514123/68197299-fe982e00-fff4-11e9-9bea-f838a28853b9.png)

 align: 'center', className: 'sku', width: 90, fixed: 'left',

**Comment by LBC100** [comment]
两列数据如下:
![image](https://user-images.githubusercontent.com/38514123/68197715-aca3d800-fff5-11e9-9eec-d84d68c82384.png)

超过11个列后又变为正常

**Comment by andyyxw** [comment]
固定列样式是有问题

**Comment by Taymindis** [comment]
你是怎麼把全選配置在下方的？ 能不能分享？

**Comment by LBC100** [comment]
> 你是怎么把全选配置在下方的？能不能分享？

![image](https://user-images.githubusercontent.com/38514123/68522383-becb9200-02e5-11ea-9ffb-9f2aada7c522.png)

pagination={paginationProps}

**Comment by Taymindis** [comment]
至於你的問題， 你要確保你每個col 的width 都分配到剛剛好填滿table的width， 如果可以的話，放destory: true, 這位developer他放錯了， 應該放 destroy

**Comment by wubostc** [comment]
你能复现问题在codesandbox上吗

**Comment by andyyxw** [comment]
> 至於你的問題， 你要確保你每個col 的width 都分配到剛剛好填滿table的width， 如果可以的話，放destory: true, 這位developer他放錯了， 應該放 destroy

表格的宽度很多时候要适配屏幕，就是不固定的，怎么做到`刚好填满`呢？ `antd` 是留出来一列宽度不定宽来适配宽度。但使用 `VTComponents` 后，宽度计算有问题

**Comment by Taymindis** [comment]
> > 至於你的問題， 你要確保你每個col 的width 都分配到剛剛好填滿table的width， 如果可以的話，放destory: true, 這位developer他放錯了， 應該放 destroy
> 
> 表格的宽度很多时候要适配屏幕，就是不固定的，怎么做到`刚好填满`呢？ `antd` 是留出来一列宽度不定宽来适配宽度。但使用 `VTComponents` 后，宽度计算有问题

用最新的react usecallback 吧， 它能給你寬度， getBounding.... 什麼什麼的。 我是用在於ReactNativeWeb Dimension 能給我寬度

**Comment by wubostc** [comment]
> > > 至於你的問題， 你要確保你每個col 的width 都分配到剛剛好填滿table的width， 如果可以的話，放destory: true, 這位developer他放錯了， 應該放 destroy
> > 
> > 
> > 表格的宽度很多时候要适配屏幕，就是不固定的，怎么做到`刚好填满`呢？ `antd` 是留出来一列宽度不定宽来适配宽度。但使用 `VTComponents` 后，宽度计算有问题
> 
> 用最新的react usecallback 吧， 它能給你寬度， getBounding.... 什麼什麼的。 我是用在於ReactNativeWeb Dimension 能給我寬度， 我之前也有這問題， 那是因為我要user能隨時加減column 而出現的空白格，但我放了destroy之後，這問題再也不會出現了，我很難浮現在codesandbox因為那是nativeweb

我明天写一个测试用例来验证column变动是否会有bug

**Comment by wubostc** [comment]
明天修复

**Comment by LBC100** [comment]
> > 为了你的问题，你要确保你每个col的宽度都分配到刚刚好填满表的宽度，如果可以的话，放destory：true，这位开发商他放错了，应该放destroy
> 
> 表格的宽度很多时候要调整屏幕，就是不固定的，怎么做到`刚好填满`呢？`antd`是留出来一列宽度不定宽来隔开宽度。但使用`VTComponents`后，宽度计算有问题

这位朋友说得对, 目前宽度计算的逻辑是: 要确保你每个col的宽度都分配到刚刚好填满表的宽度. 现在我已经解决了. 解决方案是: 获取表格的宽度, 根据表格的总宽度动态改变col的宽度.

**Comment by wubostc** [comment]
更新一下版本就好了

**Comment by Taymindis** [comment]
> 更新一下版本就好了

我更新了之後， 這兩個問題一直不斷浮現 :(

![image](https://user-images.githubusercontent.com/14217761/69248338-153ea780-0be7-11ea-9269-68892b2d71f3.png)

**Comment by wubostc** [comment]
> > 更新一下版本就好了
> 
> 我更新了之後， 這兩個問題一直不斷浮現 :(
> 
> ![image](https://user-images.githubusercontent.com/14217761/69248338-153ea780-0be7-11ea-9269-68892b2d71f3.png)

你能把问题复现出来吗？

**Comment by Taymindis** [comment]
> > > 更新一下版本就好了
> > 
> > 
> > 我更新了之後， 這兩個問題一直不斷浮現 :(
> > ![image](https://user-images.githubusercontent.com/14217761/69248338-153ea780-0be7-11ea-9269-68892b2d71f3.png)
> 
> 你能把问题复现出来吗？

我把問題解決了， 因為我之前做了condition rendering 類似

```
if(!tableLoading) { return <Table VTCom.... />;  }

return <OnLoading.... />;

```

但是我換成 
```<Table loading={tableLoading} VTCom.... /> ```
問題就解決了

**Comment by wubostc** [comment]
> 
> 
> > > > 更新一下版本就好了
> > > 
> > > 
> > > 我更新了之後， 這兩個問題一直不斷浮現 :(
> > > ![image](https://user-images.githubusercontent.com/14217761/69248338-153ea780-0be7-11ea-9269-68892b2d71f3.png)
> > 
> > 
> > 你能把问题复现出来吗？
> 
> 我把問題解決了， 因為我之前做了condition rendering 類似
> 
> ```
> if(!tableLoading) { return <Table VTCom.... />;  }
> 
> return <OnLoading.... />;
> ```
> 
> 但是我換成
> `<Table loading={tableLoading} VTCom.... /> `
> 問題就解決了

新版本应该能修复你的问题
