### ISSUE TITLE
offsetHeight instead of clientHeight

### ISSUE THREAD

**Issue by Frozzy6** [wubostc/virtualized-table-for-antd#2]
Hey, I found that when I'm using some elements with border table size less then clientHeight + border.
But if replace to offsetHeight everything is good.

https://github.com/wubostc/virtualized-table-for-antd/blob/1d147f386537bf4c5c9464ad2e90a32c3f8660bf/src/index.tsx#L119

https://github.com/wubostc/virtualized-table-for-antd/blob/1d147f386537bf4c5c9464ad2e90a32c3f8660bf/src/index.tsx#L129

**Comment by wubostc** [comment]
thanks @Frozzy6 , i have published to npm repository, please update to enjoy!

**Comment by Frozzy6** [comment]
@wubostc Thanks you for such fast answer!

It doesn't work as well with clientHeight as with offsetHeight

![image](https://user-images.githubusercontent.com/6423399/57727943-5df73000-769b-11e9-89ab-d6ecdaed0516.png)

there is an [example jsfiddle](https://jsfiddle.net/g9xmer7y/) about difference

**Comment by Frozzy6** [comment]
That's a [PR](https://github.com/wubostc/virtualized-table-for-antd/pull/3)
