### ISSUE TITLE
升级到0.6.1后插入不了数据

### ISSUE THREAD

**Issue by stevenjlho** [wubostc/virtualized-table-for-antd#22]
> index.js:659 Assertion failed: failed to free this tr[1]
使用官方的quick start例子，一样会报上面的错误。

**Comment by wubostc** [comment]
你把插入前后debug信息给我看看，包括diagnosis

**Comment by stevenjlho** [comment]
![QQ20191119-110150](https://user-images.githubusercontent.com/523963/69112774-1921db00-0abc-11ea-9f89-551f50118605.png)

0.5.5版本还是可以的，升级到0.6.1后就不行了

**Comment by wubostc** [comment]
> 
> 
> ![QQ20191119-110150](https://user-images.githubusercontent.com/523963/69112774-1921db00-0abc-11ea-9f89-551f50118605.png)
> 
> 0.5.5版本还是可以的，升级到0.6.1后就不行了

不是，你得点击展开来不然我看不到我想要的，你能放到codesandbox上吗？

**Comment by wubostc** [comment]
还有，是插入前的debug和插入后的debug，图片是分开的。。。你让我怎么看-=

**Comment by stevenjlho** [comment]
我试了codesanbox的例子是没有问题的，还是我自己定位下问题吧，谢谢

**Comment by stevenjlho** [comment]
插入前
![QQ20191119-164954](https://user-images.githubusercontent.com/523963/69131119-c3b1f200-0aec-11ea-98f6-050b10bc5916.png)

插入后
![QQ20191119-165035](https://user-images.githubusercontent.com/523963/69131140-d2000e00-0aec-11ea-9963-e87b626f6cd8.png)

我发现是因为调用free_h_tr方法时 ctx的 rowHeight数组只有一个，导致报错，估计是跟我用react hooks设置dataSource有关的

**Comment by wubostc** [comment]
我觉得你最好能把问题复现出来，并放到codesandbox上

**Comment by wubostc** [comment]
你也可以用我test目录来测试

**Comment by wubostc** [comment]
正常情况下应该不会出现第一张图那种情况
