### ISSUE TITLE
固定列后行的高度不一致导致错位

### ISSUE THREAD

**Issue by LBC100** [wubostc/virtualized-table-for-antd#23]
![image](https://user-images.githubusercontent.com/38514123/69207592-4ab5a780-0b8b-11ea-919a-aac9064ecff0.png)

title: 'SKU', dataIndex: 'sku', align: 'center', className: 'sku', width: 65, fixed: 'left',

**Comment by wubostc** [comment]
你禁用VT试试

**Comment by LBC100** [comment]
![image](https://user-images.githubusercontent.com/38514123/69207863-6a010480-0b8c-11ea-8bb4-68348d049f0b.png)
好像是这里的高度不一致导致的
