### ISSUE TITLE
最新版本不支持ie浏览器么？

### ISSUE THREAD

**Issue by lemonzoey** [wubostc/virtualized-table-for-antd#24]
我使用之前的0.4.0版本出现了个bug,当数据量很大时候，第一次加载只会加载20多条，下面都是空白的。所以我就把版本升级到最新的0.6.1版本，在这个版本上没有上面那个bug了，可是在ie11下就报错了

**Comment by wubostc** [comment]
提示报什么错？

**Comment by lemonzoey** [comment]
Error: Please using the modern browers or appropriate polyfill!
![image](https://user-images.githubusercontent.com/25550414/69222181-e529e100-0bb3-11ea-9f41-3d057fba8a1d.png)
就报这个错

**Comment by wubostc** [comment]
你得装一个requestAnimationFrame的polyfill

**Comment by lemonzoey** [comment]
好的呢，谢谢大神赐教，我试试
