### ISSUE TITLE
当数据条数初始为0 到 数十条数据的时候, 会渲染不出来一条数据

### ISSUE THREAD

**Issue by crawler-django** [wubostc/virtualized-table-for-antd#25]
直接上codesandbox. 链接: https://codesandbox.io/s/epic-fast-l79vt.

只要我将_repainting里面的代码调整一下位置即可正常运行.
原:
`

    if (PAINT_FREE.size) {
      for (let idx of PAINT_FREE) {
        free_h_tr(ctx, idx);
      }
      console.assert(!isNaN(ctx.computed_h) && ctx.computed_h >= 0);
    }

    if (PAINT_SFREE.size) {
      for (let idx of PAINT_SFREE) {
        free_h_tr(ctx, idx);
      }
      console.assert(!isNaN(ctx.computed_h) && ctx.computed_h >= 0);
    }

    if (PAINT_ADD.size) {
      for (let [idx, el] of PAINT_ADD) {
        apply_h(ctx, idx, el.offsetHeight);
      }
      console.assert(!isNaN(ctx.computed_h) && ctx.computed_h >= 0);
    }
`

改成: 
`

        if (PAINT_FREE.size) {
            for (let idx of PAINT_FREE) {
                free_h_tr(ctx, idx)
            }
            console.assert(!isNaN(ctx.computed_h) && ctx.computed_h >= 0);
        }

        if (PAINT_ADD.size) {
            for (let [idx, el] of PAINT_ADD) {
                apply_h(ctx, idx, el.offsetHeight)
            }
            console.assert(!isNaN(ctx.computed_h) && ctx.computed_h >= 0);
        }

        if (PAINT_SFREE.size) {
            for (let idx of PAINT_SFREE) {
                free_h_tr(ctx, idx)
            }
            console.assert(!isNaN(ctx.computed_h) && ctx.computed_h >= 0);
        }
`
就可以正常运行了. 初始为0的时候 两次free会报错, 所以我将add放在sfree前面就能正常运行了.
_repainting这部分代码感觉是有些重复的操作, 如果代码写的更规范一些, 不那么杂乱, 说不定会有更多的人来帮你一起维护.

**Comment by wubostc** [comment]
首先感谢你的工作！
刚刚检查了一下，代码应该是有bug的，估计是上次加了一个状态产生的，我马上修改一下@ crawler-django

**Comment by wubostc** [comment]
还有FREE和SFREE之前必然已经有对应的ADD和SADD执行过了，不会存在你那种情况free一个undefine

**Comment by crawler-django** [comment]
前提的记录信息操作:
1. 在进入srs_diff之前

`

    let SR_n2delete = 0, SR_n2insert = 0
    console.log(
        `PSRA ${PSRA}, PSRB ${PSRB}, len ${len}, prev_len ${prev_len}, head ${head}, tail ${tail}`
    )
    ...
`

2. 进入srs_diff

`

    console.log(
        `PSR ${PSR}, begin ${begin}, end ${end}, prev_begin ${prev_begin}, prev_end ${prev_end}`
    )
    const { row_height, possible_hight_per_tr } = ctx
    ...
`

3. 在_repainting中

`

    const { PAINT_ADD, PAINT_SADD, PAINT_FREE, PAINT_SFREE } = ctx
    console.log('=====repainting======')
    console.log('PAINT_ADD', PAINT_ADD)
    console.log('PAINT_SADD', PAINT_SADD)
    console.log('PAINT_FREE', PAINT_FREE)
    console.log('PAINT_SFREE', PAINT_SFREE)
    console.log('=====repainting======')
`

-------------------------------分割线----------------------------------

执行结果:
1. 从0渲染到297条数据的时候:

- [ ] 第一次渲染打印(NEITHER): (可以进入srs_diff的第一次)
 
          > 进入diff前: PSRA -1,-1, PSRB -1,-1, len 297, prev_len 297, head 0, tail 1

          判断PSRB[0] === -1

          > 进入diff里: PSR -1,-1, begin 1, end 297, prev_begin 1, prev_end 1

          此时会进入PAINT_SADD 的 add,  PAINT_SADD会增加到297条, size为297.

          ====================================================

          判断PSRA[0] === -1

          > 进入diff里: PSR -1,-1, begin 0, end 0, prev_begin 0, prev_end 0

          此时会进入VTRow的componentDidUpdate. 进行一次repainting_with_free和repainting_with_add.

- [ ] 第二次渲染打印(NEITHER):

          > 进入diff前: PSRA 0,0, PSRB 1,297, len 297, prev_len 297, head 0, tail 1

          判断PSRB[0].

          > 进入diff里: PSR 1,297, begin 1, end 297, prev_begin 1, prev_end 297
     
          ===================================================

          判断PSRA[0]

          > 进入diff里: PSR 0,0, begin 0, end 0, prev_begin 0, prev_end 0

          此时会进VTRow的componentDidUpdate. 进行一次的repainting_with_add, 但是index和第一次是一样的.

- [ ] 第三次渲染打印(NEITHER):
          重复第二次的操作.... 都会进行一次repainting_with_add, index还是一样的.这里一共重复了三四次.(不过是没有影响的, 只是我啰嗦)

- [ ] 有改变的打印(NEITHER):

          > 进入diff前: PSRA 0,0, PSRB 1,297, len 297, prev_len 297, head 0, tail 24

          判断PSRB[0].
          
          > 进入diff里: PSR 1,297, begin 24, end 297, prev_begin 1, prev_end 297

          然后此时会进入PAINT_SFREE 的 add, 增加到23条. 

          =====================================================
 
          判断PSRA[0]

          > 进入diff里: PSR 0,0, begin 0, end 0, prev_begin 0, prev_end 0

          此时会进入VTRow的componentDidUpdate, 会执行23次的repainting_with_add. 但是Index是一样的.。

- [ ] 终于到了_repainting执行的时候了:

              =====repainting======
              PAINT_ADD => Map(24)
              PAINT_SADD => Map(296)
              PAINT_FREE => Set(1)
              PAINT_SFREE => Set(23)
              =====repainting======

此时先两次free在先执行的就会报错, 因为此时的ctx.row_height数组只有一个值, row_height赋值的操作在apply_h, 我看了一下apply_h这个函数的调用, 只有三次, 一次初始化componentDidMount的时候调用, 两次都只能在_repainting函数里调用.  

你说的每次FREE SFREE之前都会有ADD SADD执行过了, 那是不是我的requestAnimationFrame 被卡住了? 在最后的时候(离报错前最近的)才执行.

题外话:  table组件的key 和 dataIndex 其实差不多, 官网有, 只是我这边用它来区分一些操作.  不支持远程

**Comment by Taymindis** [comment]
我覺得你放rowKey 吧， 這麼重要的東西都沒放到呢， uniq key 不一樣數據截然有問題

**Comment by wubostc** [comment]
@crawler-django 你现在是什么运行环境？

**Comment by crawler-django** [comment]
> @crawler-django 你现在是什么运行环境？

chrome 版本78.0.3904.108

**Comment by wubostc** [comment]
> > @crawler-django 你现在是什么运行环境？
> 
> chrome 版本78.0.3904.108
> react 16.12.0
> antd ~3.25.2
> ts ^3.7.2
> 
> 我测试环境应该是这样

我下午有事，你有什么好办法解决，如果是像之前那样调换一下位置肯定是不行的。

**Comment by wubostc** [comment]
@crawler-django 为什么第一次渲染你会进入VTRow的componentDidUpdate？
我实在是没法复现你的问题，你看这次提交能否解决你的问题？

**Comment by crawler-django** [comment]
已解决

**Comment by crawler-django** [comment]
最新的代码没有问题了

**Comment by Taymindis** [comment]
@wubostc 這次的提交有release version 嗎？ 我想全面更新version。 謝謝您

**Comment by wubostc** [comment]
> 
> 
> @wubostc 這次的提交有release version 嗎？ 我想全面更新version。 謝謝您

目前还没有。

**Comment by wubostc** [comment]
我已经发布新版本了------------------ 原始邮件 ------------------
发件人: "Taymindis Woon"<notifications@github.com>
发送时间: 2019年11月24日(星期天) 中午11:28
收件人: "wubostc/virtualized-table-for-antd"<virtualized-table-for-antd@noreply.github.com>;
抄送: "wubostc"<913721086@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [wubostc/virtualized-table-for-antd] 当数据条数初始为0 到 数十条数据的时候, 会渲染不出来一条数据 (#25)



@wubostc 這次的提交有release version 嗎？ 我想全面更新version。 謝謝您
 
&mdash;
