### ISSUE TITLE
How to use custom row component?

### ISSUE THREAD

**Issue by yss14** [wubostc/virtualized-table-for-antd#26]
Hey :)

I don't quite get how to use my custom row component with your library.

Before I just used:
```typescript
<Table
	columns={columns}
	dataSource={songs}
	pagination={false}
	scroll={{ y: height - 210 }}
	components={{ body: { row: MyCustomRowComponent } }}
/>
```

Now I tried

```typescript
const componentsConfig = getVTComponents(1000);
componentsConfig.row = MyCustomRowComponent

<Table
	columns={columns}
	dataSource={songs}
	pagination={false}
	scroll={{ y: height - 210 }}
	components={
		VTComponents({
			id: 1000,
		})
	}
/>
```
but I get a `Assertion failed: console.assert` on the console without any further explanation what's wrong.

**Comment by wubostc** [comment]
Hello @yss14 .
There is currently no way to support your custom row, I will give you a solution as soon as possible in the next version.

**Comment by yss14** [comment]
@wubostc Just pulled the latest changes from your `0.6` branch and tried it locally with my project. It works like a charm! And I also really like the new API `setComponents` :)
Thank you very much for your work! Looking forward to the new version release.

**Comment by wubostc** [comment]
I've released the new version to NPM.
