### ISSUE TITLE
Ajax for progressive load

### ISSUE THREAD

**Issue by ponsifiax** [wubostc/virtualized-table-for-antd#27]
Hello,

Are you plan to create an example to work with ajax content progressive loading ?

Thank you.

**Comment by ponsifiax** [comment]
Thx for your reactivity. 

But your code is only for first loading, not progressive loading in ajax.
In my case, to improve loading of very big number of elements (i know the total number of elements - more than 100 000), i need load by chunck, by example load first 1000 elements from ajax and load next 200 when the virtualize view is on the end of the loaded elements.

Do you have nay way to do that?

Thank you in advance.

**Comment by wubostc** [comment]
I just wanna change the param of the `onScroll`.
like this.
```
VTComponents({
id: 1,
onScroll({ left, top, isEnd, }) {
  if (isEnd) {
    // load by chunk.
  }
}
});
```

Do you have any good idea?
