### ISSUE TITLE
多个列表切换的时候，高度会出现问题

### ISSUE THREAD

**Issue by victorWuxz** [wubostc/virtualized-table-for-antd#32]
![image](https://user-images.githubusercontent.com/36194121/70500770-4e6b9700-1b57-11ea-98a7-03a3199c44d0.png)
![image](https://user-images.githubusercontent.com/36194121/70500799-57f4ff00-1b57-11ea-938c-f26949b5e656.png)

**Comment by victorWuxz** [comment]
![image](https://user-images.githubusercontent.com/36194121/70500843-70651980-1b57-11ea-893c-31625fde22eb.png)

**Comment by victorWuxz** [comment]
![image](https://user-images.githubusercontent.com/36194121/70500884-91c60580-1b57-11ea-9102-a20302d19280.png)

**Comment by wubostc** [comment]
试试新版
