### ISSUE TITLE
为什么只做了computed_h >=0 的断言，没有强制最小值为0

### ISSUE THREAD

**Issue by ICELI** [wubostc/virtualized-table-for-antd#34]
当1条数据更新为0条数据时，srs_diff方法中会加入一条sfree，导致渲染时computed_h小于0，table高度更新就出问题了。
解决：
1. 优化srs_diff里的逻辑
2. 强制computed_h最小值为0

总之都是需要熟悉原有逻辑...

**Comment by wubostc** [comment]
新版应该解决了
