### ISSUE TITLE
Table becomes blank when it re-renders

### ISSUE THREAD

**Issue by sai78** [wubostc/virtualized-table-for-antd#35]
![issue](https://user-images.githubusercontent.com/34151355/70925388-24334100-2051-11ea-9dc0-735ccb61f18b.PNG)
We have a table component that fetches new data on page change or on sorting etc. It goes blank sometimes and the issue is difficult to reproduce.  Similar to issue #15. Can you help me in resolving this issue

**Comment by sai78** [comment]
We are getting 'Assertion failed: console.assert' errors whenever the issue occurs on this line **console.assert(ctx.vt_state === e_VT_STATE.SUSPENDED);**

**Comment by wubostc** [comment]
Can you provide me more information about debug?

**Comment by wubostc** [comment]
The new version may solve your issue.

**Comment by sai78** [comment]
The new version had resolved the issue. Thank you @wubostc.
