### ISSUE TITLE
Add React, react dom and antd to peerdependencies rather than dependencies

### ISSUE THREAD

**Issue by Taymindis** [wubostc/virtualized-table-for-antd#38]
"peerDependencies": {
    "antd": "^3.x",
    "react": "16.x",
    "react-dom": ...
  },

我覺得你應該把這3個library移去 peerDepencies， 因為我的library若有你的dependencies就會造成react duplication。

**Comment by wubostc** [comment]
不会的

**Comment by JhonXY** [comment]
> 不会的

所有的 dependencies 应该都 移去 peerDepencies，这样能避免包内不必要的 node_modules，尤其是外部装了 antd 的时候:
![image](https://user-images.githubusercontent.com/21687167/94111425-9ce3eb00-fe76-11ea-9851-83471ea1b2f2.png)

**Comment by wubostc** [comment]
移了XD
