### ISSUE TITLE
Fixed row height

### ISSUE THREAD

**Issue by Frozzy6** [wubostc/virtualized-table-for-antd#4]
Hello, I need a possibility to set **this.inst.current.offsetHeight** by hands. There are exist cases when offsetHeight equals to zero and table didn't show any content.
It looks like 
![image](https://user-images.githubusercontent.com/6423399/58640325-7e60f480-8301-11e9-8203-ffb8c9313dbd.png)
I sometimes got this issue with dynamic components.

Can you do props param for fixed row height smth like
`
this.collect_h_tr(this.props.children[0]!.props!.index, this.props.rowHeight || this.inst.current.offsetHeight);
`
in didmount and didupdate methods?

**Comment by wubostc** [comment]
Thanks, could you put your code to https://codesandbox.io/embed/m7j063zy89 for reproduction

**Comment by wubostc** [comment]
Hey @Frozzy6 , use the option Table.locale.emptyText to resolve your problem.
This virtualized-table-for-antd only used for VIRTUALIZATION.
