### ISSUE TITLE
现在还有一个问题 当fixed=‘right’ 时 主table和right table 中间会有一个滚动条的空白，这个修复有思路吗？

### ISSUE THREAD

**Issue by Nokecy** [wubostc/virtualized-table-for-antd#41]
现在还有一个问题 当fixed=‘right’ 时 主table和right table 中间会有一个滚动条的空白，这个修复有思路吗？
![image](https://user-images.githubusercontent.com/12318131/59911319-320f5d00-9446-11e9-8d80-7f1f93e51300.png)

_Originally posted by @Nokecy in https://github.com/wubostc/virtualized-table-for-antd/issues/9#issuecomment-504351225_

**Comment by Nokecy** [comment]
[https://codesandbox.io/embed/crazy-kilby-2l9i1](https://codesandbox.io/embed/crazy-kilby-2l9i1)  最新版本也有这个问题

**Comment by wubostc** [comment]
这里的 height 属性不需要了，填了可能会报错 @Nokecy

**Comment by wubostc** [comment]
应该没什么问题，我直接发布新版了
