### ISSUE TITLE
Table scrolls more than necessary and headers are not scrolled

### ISSUE THREAD

**Issue by nadunindunil** [wubostc/virtualized-table-for-antd#44]
We were using v0.7.1 and when updated to v0.7.5, table scroller try to scroll more than the table width. Not only scroll but also header is not scrolling as it supposed to be.
When we dig deeper we found that the table body width is changed to 100000.
1. width
![Screen Shot 2020-01-01 at 4 17 16 PM](https://user-images.githubusercontent.com/9638054/71640634-bb380400-2cb3-11ea-930e-a83f6deb4750.png)

2. scroller error
![Screen Shot 2020-01-01 at 4 08 58 PM](https://user-images.githubusercontent.com/9638054/71640635-bb380400-2cb3-11ea-9d2b-5826d619e8b8.png)
![Screen Shot 2020-01-01 at 4 09 21 PM](https://user-images.githubusercontent.com/9638054/71640636-bb380400-2cb3-11ea-88e6-1bc6a9e2e70a.png)

**Comment by wubostc** [comment]
@nadunindunil thx.
Could you please reproduce your issues on codesandbox?
