### ISSUE TITLE
ctx._React_ptr.forceUpdate is not a function. 

### ISSUE THREAD

**Issue by njacob1001** [wubostc/virtualized-table-for-antd#46]
I'm using React-router-dom and when I change to other screen with te same Table component but with differenrent data, appears whits error, however the Table works

`Uncaught TypeError: ctx._React_ptr.forceUpdate is not a function vt.js:249`

**Comment by njacob1001** [comment]
commit #46 didn't fix the issue

**Comment by wubostc** [comment]
@njacob1001 Could you reproduce your issue on codesandbox?

**Comment by wubostc** [comment]
Hello, @njacob1001 , Did this commit|(32ed649) solve your problem?

**Comment by nadunindunil** [comment]
when is the next release with this issue fixed

**Comment by wubostc** [comment]
> 
> 
> when is the next release with this issue fixed

@njacob1001

**Comment by wubostc** [comment]
@njacob1001  I will not release a new version until I solve this issue. :P

**Comment by nadunindunil** [comment]
hi, any update ?

**Comment by wubostc** [comment]
i've just pushed 0.7.6 to NPM,
it should solve this problem, though i haven't tested it...

**Comment by matteocollina** [comment]
In version 0.7.8 there is still the error.
`
TypeError e._React_ptr.forceUpdate is not a function 
    ../node_modules/virtualizedtableforantd/es/vt.js:424 _RC_rerender
    ../node_modules/virtualizedtableforantd/es/vt.js:1244 a.value
`
