### ISSUE TITLE
[功能请求] 支持ant 4.0.0-rc0

### ISSUE THREAD

**Issue by Nokecy** [wubostc/virtualized-table-for-antd#47]

**Comment by wubostc** [comment]
4.0不是原生支持的吗

**Comment by Nokecy** [comment]
[https://next.ant.design/components/table-cn/#components-table-demo-virtual-list](https://next.ant.design/components/table-cn/#components-table-demo-virtual-list)  只是一个demo 其他功能全部没有了，比如固定列之类的

**Comment by wubostc** [comment]
> 
> 
> https://next.ant.design/components/table-cn/#components-table-demo-virtual-list 只是一个demo 其他功能全部没有了，比如固定列之类的

想要兼顾两个大版本似乎是不太现实

**Comment by wubostc** [comment]
看一下 #66
