### ISSUE TITLE
多条数据并存在复选框的情况下，性能问题

### ISSUE THREAD

**Issue by FAKER-A** [wubostc/virtualized-table-for-antd#49]
4000+条数据，全选的情况下 渲染需要4~5s, 改变全选状态也需要大概这么长时间，老哥有啥好的想法改善嘛
![image](https://user-images.githubusercontent.com/25676164/71883096-a4405880-3170-11ea-9fa5-5aa60e35833c.png)

**Comment by wubostc** [comment]
不是我的问题呀
