### ISSUE TITLE
不支持 fixed 

### ISSUE THREAD

**Issue by Nokecy** [wubostc/virtualized-table-for-antd#5]
https://codesandbox.io/embed/antd-reproduction-template-b8uqh

**Comment by wubostc** [comment]
了解，我调查一下

**Comment by Nokecy** [comment]
大佬有什么想法吗~~~~

**Comment by wubostc** [comment]
fixed不区分 Table的components的table，所以不管是fixedleft、fixedright、还是没有fixed的，都是同一个table组件，这就很尴尬，所以第一步得想办法区分开来才好做。

**Comment by Nokecy** [comment]
主要好像是storeValue用到同一个对象了吧

**Comment by wubostc** [comment]
这个没错的，原因是我刚刚说了是现在还没法区分fixedleft、fixedright和没有fixed的组件，刚刚我开了一个新分支，目前还有一些问题，你可以尝试一下看看。

**Comment by wubostc** [comment]
现在只差VTRow的区分还有些问题。。。

**Comment by Nokecy** [comment]
VTRow 可以再包一层 ，但是貌似还是有点问题https://codesandbox.io/s/crazy-darkness-m6rml

**Comment by Nokecy** [comment]
https://codesandbox.io/s/crazy-darkness-m6rml @wubostc

**Comment by wubostc** [comment]
Fixed分支提交了，初步支持fixed选项。@Nokecy

**Comment by Nokecy** [comment]
大佬 期待合并 发版哦~~~

**Comment by Nokecy** [comment]
#6
