### ISSUE TITLE
The table will not render while the data in redux have not change

### ISSUE THREAD

**Issue by milkrong** [wubostc/virtualized-table-for-antd#51]
My table is data is from redux soldiers as below
```
const INITIAL_STATE = {
  soldiers: [],
  isLoading: false,
  currentPage: 0,
  keyword: '',
  sortProperty: '',
  sortDirection: '',
  isDetail: false,
  skip: 'false'
};
```
Somtimes I  will jump to another component with router. After back to  the table, if the data in redux not change, the table will not render and just display the header.

<img width="1165" alt="WX20200113-182138@2x" src="https://user-images.githubusercontent.com/15906981/72308663-bff4a480-3631-11ea-8aef-990d5500c226.png">
<img width="1185" alt="WX20200113-182201@2x" src="https://user-images.githubusercontent.com/15906981/72308677-c5ea8580-3631-11ea-8bba-7f6cc50a9861.png">

Actually I have data in redux
<img width="443" alt="WX20200113-182222@2x" src="https://user-images.githubusercontent.com/15906981/72308711-d864bf00-3631-11ea-831b-416967890bfe.png">

It seems that if the data in the redux, not updates, the table will not render.

**Comment by wubostc** [comment]
Could you reproduce your issue in codesandbox?

**Comment by wubostc** [comment]
@milkrong Are there any errors in console?

**Comment by wubostc** [comment]
there is a example [here](https://github.com/wubostc/virtualized-table-for-antd/blob/master/test/reload.tsx), you can refer to it.

**Comment by milkrong** [comment]
@wubostc I will reproduce it know.  I can see the rows with the dev tool. Actually there are rows there, but nothing has shown that I can see. It just looks like blank blocks

**Comment by milkrong** [comment]
@wubostc [CodeSandbox](https://codesandbox.io/s/eloquent-benz-0kitb?fontsize=14&hidenavigation=1&theme=dark
)
you can try this. Once I click the link on the top to another page, and click go-back button on the browser.  The table will not render correctly, and actually you can see there are users printed in the console. (every time the data in redux will be the same.

It seems that if there is no state updated, the rows will disappear. And I have to solve this problem by force the state in redux updated every time ( I clear the data to empty and reload them)

**Comment by wubostc** [comment]
@milkrong Great job.
I just change your some code to works well you can see later.

There are some problems in calling setTop within onscroll, because setTop belongs to Redux, you can call it in unmount to prevent rerender with scrolling event.

**Comment by wubostc** [comment]
https://codesandbox.io/s/dazzling-shannon-iz2xj
