### ISSUE TITLE
大量数据且columns设置了fixed后，会出现2个滚动条，表格错位

### ISSUE THREAD

**Issue by OneMay** [wubostc/virtualized-table-for-antd#52]
![b16fef70-cd8e-4e51-b683-7fec7d0c341b](https://user-images.githubusercontent.com/20608989/72329786-58515e80-36f0-11ea-901a-ed88b85d4a05.png)

地址：[stackblitz](https://stackblitz.com/edit/react-wu1twh?file=index.js)

**Comment by wubostc** [comment]
你把components属性去了试试，我这半天打不开

**Comment by OneMay** [comment]
> 你把components属性去了试试，我这半天打不开

试了一下，似乎是antd本身的问题~
