### ISSUE TITLE
Getting error 'Assertion failed' when used with Transfer

### ISSUE THREAD

**Issue by chinhoe** [wubostc/virtualized-table-for-antd#53]
When used together with antd's Transfer component, i get the error when trying to transfer data from one side to another. Performing the same action furthermore will crash my app.

Demo: [https://codesandbox.io/s/morning-grass-o010b](https://codesandbox.io/s/morning-grass-o010b)

![image](https://user-images.githubusercontent.com/15047293/73711544-27d67080-4742-11ea-91bf-0febf82919e5.png)

**Comment by wubostc** [comment]
@chinhoe
A VT can only be used by one Table instance.

Here the ```<Table/>``` is actually rendered twice. it's okay, but that also causes the VT(```components={VirtualTable}```) to be rendered twice by the parent node ```<Table/>```, which will cause some problems...

**Comment by wubostc** [comment]
At the moment, it seems to only be able to write like this.

```components={isLeft ? LVirtualTable : RVirtualTable}```

**Comment by wubostc** [comment]
and，I suggest you encapsulate your Table like
```
function MyTable(props) {
  const [VT] = useVT();
  return <Table {...props} components={VT} />
}
```

in my opinion it should work just fine
