### ISSUE TITLE
仅仅跑了源码下 test文件下的文件,报一下错误(接不进自己的项目,请问是什么原因???)

### ISSUE THREAD

**Issue by 18487115313** [wubostc/virtualized-table-for-antd#55]
"react": "16.12.0",
"antd": "^4.0.3",
"virtualizedtableforantd": "^0.7.6"
使用的是 : useVT
然后将你Test中CustomRows Hooks取出来放到我项目中测试,结果报错
[
  Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
]

使用  components={VTComponents({ id: 1, debug: true })}
报错 
[
 vt.js文件  TypeError: Cannot read property 'props' of undefined;
The above error occurred in the <VTable> component:
    in VTable (created by Table)
    in div (created by Table)
    in div (created by Table)
    in Unknown
]

**Comment by 18487115313** [comment]
复现地址 :https://codesandbox.io/s/gallant-glitter-j1yj9

**Comment by wubostc** [comment]
研究了一会儿，应该是react render机制会打断组件渲染，导致重复new了2次渲染了2次
还有一个问题是antd  4 并不支持

**Comment by wubostc** [comment]
@18487115313 我待会儿提交一下修复

**Comment by 18487115313** [comment]
@wubostc 有考虑支持 antd 4.0吗

**Comment by wubostc** [comment]
> 
> 
> @wubostc 有考虑支持 antd 4.0吗

4.0按官方所说会原生支持的

**Comment by wubostc** [comment]
> @wubostc 有考虑支持 antd 4.0吗

支持了4.0
