### ISSUE TITLE
多个Tab切换，table为tab的内容，table的body高度为0，页面展示为空白

### ISSUE THREAD

**Issue by ZoeNa-Li** [wubostc/virtualized-table-for-antd#58]
![image](https://user-images.githubusercontent.com/22948477/79098310-4edd9e00-7d94-11ea-86ee-0e9e903b6cd0.png)

![image](https://user-images.githubusercontent.com/22948477/79098434-88aea480-7d94-11ea-85c5-f0b72b7a0a22.png)

**Comment by wubostc** [comment]
没有复现地址的会被关闭issue
