### ISSUE TITLE
size props not work

### ISSUE THREAD

**Issue by 7inFen** [wubostc/virtualized-table-for-antd#59]
这是一个在线Demo（取消components相关代码会报错，但是在本地可以重现）
https://stackblitz.com/edit/react-gdqekr

应用VTComponents的components后，antd的size属性没有生效

**Comment by running-snail-sfs** [comment]
应用VTComponents的components后直接报错

**Comment by running-snail-sfs** [comment]
> 这是一个在线Demo（取消components相关代码会报错，但是在本地可以重现）
> https://stackblitz.com/edit/react-gdqekr
> 
> 应用VTComponents的components后，antd的size属性没有生效
应用VTComponents的components后直接报错

**Comment by wubostc** [comment]
晚上我看一下

**Comment by wubostc** [comment]
目前并不兼容antd4

**Comment by 7inFen** [comment]
> 目前并不兼容antd4

ok，换成v3的包可以跑通了。
table size设置成small的时候，只有thead变小了，tbody还是default时的大小。

**Comment by running-snail-sfs** [comment]
> > 目前并不兼容antd4
> 
> ok，换成v3的包可以跑通了。
> table size设置成small的时候，只有thead变小了，tbody还是default时的大小。

你好，问下你的表格将浏览器拖动到最大，表格会错位吗？我的错位了

**Comment by 7inFen** [comment]
> > > 目前并不兼容antd4
> > 
> > 
> > ok，换成v3的包可以跑通了。
> > table size设置成small的时候，只有thead变小了，tbody还是default时的大小。
> 
> 你好，问下你的表格将浏览器拖动到最大，表格会错位吗？我的错位了

这个没有。
不过在用antd table左右列固定的时候遇到过固定列错位，当时没办法遍历设置列宽度才解决。

**Comment by wubostc** [comment]
> 
> 
> > 目前并不兼容antd4
> 
> ok，换成v3的包可以跑通了。
> table size设置成small的时候，只有thead变小了，tbody还是default时的大小。

里面的样式要自己改，因为加了一层div，你仔细看一下文档https://github.com/wubostc/virtualized-table-for-antd/blob/master/README.md
