### ISSUE TITLE
Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by GeorgeCodeHub** [wubostc/virtualized-table-for-antd#65]
I tried running an example but I seem to get an error of props undefined.

Example: https://stackblitz.com/edit/virtualizedantd

Have I forgotten to add something?

**Comment by wubostc** [comment]
Oh, @GeorgeCodeHub VT only supports antd 3.x

**Comment by GeorgeCodeHub** [comment]
Oh, I see. Thank you for answering so quickly.

**Comment by chongckw1996** [comment]
Any other solution to implement on antd 4 ?

**Comment by wubostc** [comment]
pls keep track on [this](https://github.com/wubostc/virtualized-table-for-antd/tree/dev/support-antd4) branch

**Comment by wubostc** [comment]
> pls keep track on [this](https://github.com/wubostc/virtualized-table-for-antd/tree/dev/support-antd4) branch

translated by Google
Currently implemented initially, there are still some bugs:
1. The form header is hidden
2. The table head can't move when dragging horizontally

Have not figured out how to solve it (mainly too lazy to look at the source code of antd (0x0))
Estimated for a long time

**Comment by wubostc** [comment]
#66
