### ISSUE TITLE
请问能与antd4中的compents复合一起使用吗

### ISSUE THREAD

**Issue by yyjmstar** [wubostc/virtualized-table-for-antd#67]
![image](https://user-images.githubusercontent.com/51106925/86200347-f77aed00-bb8e-11ea-8da0-21a2e7e2ff58.png)
![image](https://user-images.githubusercontent.com/51106925/86200372-0bbeea00-bb8f-11ea-951a-1ec88d7ab0a2.png)
第一张图片是虚拟滚动加载的，我想和我现在开发的表格一起联合使用，只不过现在的表格是支持行，列拖动排序，并且删除行、列的操作

**Comment by wubostc** [comment]
新版本可以支持

**Comment by wubostc** [comment]
> ![image](https://user-images.githubusercontent.com/51106925/86200347-f77aed00-bb8e-11ea-8da0-21a2e7e2ff58.png)
> ![image](https://user-images.githubusercontent.com/51106925/86200372-0bbeea00-bb8f-11ea-951a-1ec88d7ab0a2.png)
> 第一张图片是虚拟滚动加载的，我想和我现在开发的表格一起联合使用，只不过现在的表格是支持行，列拖动排序，并且删除行、列的操作

npm i --save virtualizedtableforantd4

**Comment by yyjmstar** [comment]
那写法是按照我上面第二张图片的写法吗，npm i --save virtualizedtableforantd4会不会将我本地的antd版本提升的4.0.0

**Comment by wubostc** [comment]
> 那写法是按照我上面第二张图片的写法吗，npm i --save virtualizedtableforantd4会不会将我本地的antd版本提升的4.0.0

antd3 就用0.7版本的，antd4 用1.0版本的

**Comment by yyjmstar** [comment]
有联合使用的文档吗

**Comment by wubostc** [comment]
> 有联合使用的文档吗

不能混用啊，你antd是哪个版本就用哪个vt版本

**Comment by yyjmstar** [comment]
那我本地是antd3的，是不是就想要结合着写就不行了
![image](https://user-images.githubusercontent.com/51106925/86206117-264c8f80-bb9e-11ea-9d15-ecf5e6518a09.png)
主要表格拖拽功能也要用到compents，和虚拟滚动的compents就冲突

**Comment by wubostc** [comment]
https://github.com/wubostc/virtualized-table-for-antd/blob/0.7/test/Editable%20Rows.jsx

**Comment by wubostc** [comment]
https://github.com/wubostc/virtualized-table-for-antd/blob/v3.x/test/Drag%20soring.jsx

**Comment by wubostc** [comment]
> 那我本地是antd3的，是不是就想要结合着写就不行了
> ![image](https://user-images.githubusercontent.com/51106925/86206117-264c8f80-bb9e-11ea-9d15-ecf5e6518a09.png)
> 主要表格拖拽功能也要用到compents，和虚拟滚动的compents就冲突

你看一下吧，有空帮我完善一下文档

**Comment by wubostc** [comment]
所有的改动你也可以看看change log

**Comment by yyjmstar** [comment]
好的，十分谢谢，我看一下

**Comment by yyjmstar** [comment]
再打扰下，
![image](https://user-images.githubusercontent.com/51106925/86210801-ceb32180-bba7-11ea-95a4-e7024b7814c1.png)报zhe这样的错误是为什么

**Comment by wubostc** [comment]
> 再打扰下，
> ![image](https://user-images.githubusercontent.com/51106925/86210801-ceb32180-bba7-11ea-95a4-e7024b7814c1.png)报zhe这样的错误是为什么

你得把debug打开，再把debug数据给我看一下

**Comment by yyjmstar** [comment]
![image](https://user-images.githubusercontent.com/51106925/86231686-830f7080-bbc5-11ea-9c28-90a3907d7368.png,
这个可以看出问题所在嘛

**Comment by wubostc** [comment]
> ![image](https://user-images.githubusercontent.com/51106925/86231686-830f7080-bbc5-11ea-9c28-90a3907d7368.png,
> 这个可以看出问题所在嘛

都变成undefined了，你做了啥？你能复现吗

**Comment by yyjmstar** [comment]
我什么也没干呀，我也发现了这个undefind，但是不知道你这个数据到底从何处获取的，所以定位不到问题

**Comment by yyjmstar** [comment]
你这个row_height，是从何处获取的数据

**Comment by wubostc** [comment]
你要先复现出来 这样我才好排查问题

**Comment by wubostc** [comment]
你仔细看一下测试样例 自定义row需要dom的ref
