### ISSUE TITLE
Uncaught TypeError: React.createContext is not a function 是不是因为我的antd版本太低了？

### ISSUE THREAD

**Issue by chenglijunnanduo** [wubostc/virtualized-table-for-antd#68]
![image](https://user-images.githubusercontent.com/31369989/88998438-94fb4500-d324-11ea-872a-1ada6df5b1ad.png)

**Comment by wubostc** [comment]
大哥你检查一下react版本吧

**Comment by chenglijunnanduo** [comment]
项目太大了不好改版本 换了npm提供的组件 react-virtualized
