### ISSUE TITLE
不支持表格编辑的吗

### ISSUE THREAD

**Issue by running-snail-sfs** [wubostc/virtualized-table-for-antd#69]
不支持表格编辑的吗

**Comment by wubostc** [comment]
> 不支持表格编辑的吗

可以 请看example

**Comment by running-snail-sfs** [comment]
> 以 请看e

有没有antd3.x的表格可编辑的列子

**Comment by running-snail-sfs** [comment]
> > 不支持表格编辑的吗
> 
> 可以 请看example

class 组件的可编辑行好像不行

**Comment by wubostc** [comment]
> > > 不支持表格编辑的吗
> > 
> > 
> > 可以 请看example
> 
> class 组件的可编辑行好像不行

你得切到3.x分支看啊……

**Comment by running-snail-sfs** [comment]
> > > > 不支持表格编辑的吗
> > > 
> > > 
> > > 可以 请看example
> > 
> > 
> > class 组件的可编辑行好像不行
> 
> 你得切到3.x分支看啊……

![image](https://user-images.githubusercontent.com/29230698/89528495-ba54eb00-d81d-11ea-8187-090025a68312.png)
试了3.x 设置了这个不行，去除  row:EditableFormRow, 数据展示可以，但是不能编辑

**Comment by wubostc** [comment]
https://github.com/wubostc/virtualized-table-for-antd/blob/v3.x/test/Editable%20Rows.jsx
你再看看吧 你代码明显不对

**Comment by running-snail-sfs** [comment]
> https://github.com/wubostc/virtualized-table-for-antd/blob/v3.x/test/Editable%20Rows.jsx
> 你再看看吧 你代码明显不对

感谢，搞定了。还有个问题你这个id=1000不可改，这个代表啥？

**Comment by wubostc** [comment]
> 你再看看吧 你代码明显不对

id不要重复就行了

**Comment by running-snail-sfs** [comment]
![image](https://user-images.githubusercontent.com/29230698/89707862-dd5dd700-d9a4-11ea-8367-e78ab71404c9.png)
多个不同路由下表格切换，会出现数组异常

**Comment by wubostc** [comment]
试试destroy: true

**Comment by running-snail-sfs** [comment]
> 试试destroy: true
好像可以，这个是加载的时候销毁上次的记录还是怎么样？我是不是每个需要用这个虚拟列表都要
![image](https://user-images.githubusercontent.com/29230698/89708319-9a056780-d9a8-11ea-9818-60fe4ca21c60.png)这样写
