### ISSUE TITLE
能否支持scroll={{y:"calc(100vh - 80px)"}}

### ISSUE THREAD

**Issue by Nokecy** [wubostc/virtualized-table-for-antd#7]
很多时候table的高度是通过calc计算得来的

**Comment by wubostc** [comment]
高度计算是通过指定数值来做的，calc的话该怎么弄，，
查了下度娘“calc(100vh - 10px) 表示整个浏览器窗口高度减去10px的大小”
我能否这样计算？
y：浏览器窗口高度
height = y - 10

**Comment by wubostc** [comment]
又看了下antd Table文档，scroll支持情况是{ x: number | true, y: number }，并不支持css的那种方法

**Comment by wubostc** [comment]
又去codepen调式了一下，发现居然又支持那种写法，，，

**Comment by Nokecy** [comment]
antd 文档应该没更新 ，可以使用calc(100vh - 10px)

**Comment by Nokecy** [comment]
可不可以在VT 的componentDidMount 中获取DOM的实际高度~~

**Comment by wubostc** [comment]
显然
不行

**Comment by wubostc** [comment]
@Nokecy 我刚刚又提交了，你尝试一下，应该是不再需要height了

**Comment by Nokecy** [comment]
666

**Comment by Nokecy** [comment]
可以 完美 @wubostc
