### ISSUE TITLE
v3.x版本 table设置onExpand，expandedRowRender参数，row的高度计算会出问题

### ISSUE THREAD

**Issue by luojh007** [wubostc/virtualized-table-for-antd#70]
![image](https://user-images.githubusercontent.com/48831039/90996662-02cc2100-e5f2-11ea-8bd6-05cb8efc19e9.png)
计算高度的时候，取不到index

![image](https://user-images.githubusercontent.com/48831039/90996347-17f48000-e5f1-11ea-8204-b80eb6a113fe.png)

**Comment by wubostc** [comment]
不支持多级的，非常抱歉
