### ISSUE TITLE
How to control scrollHeight

### ISSUE THREAD

**Issue by linonetwo** [wubostc/virtualized-table-for-antd#71]
Seems `virtualScrollContainer.scrollTop = virtualScrollContainer.scrollHeight;` is not working

**Comment by wubostc** [comment]
what that means?
could you show your code for that problem?

**Comment by linonetwo** [comment]
I want to scroll to the bottom of the table if new content added to it.

normally assing scrollHeight to scrollTop will move to a div's bottom, but this is not working inside virtualized-table.

**Comment by linonetwo** [comment]
Maybe what I need is a way to controll scrollbar of the virtualized-table.

**Comment by wubostc** [comment]
the `scrollTop` is controlled by the program inside vt.
and is this what you need a way?
```
    onScroll?: ({ left, top, isEnd, }: {
        top: number;
        left: number;
        isEnd: boolean;
    }) => void;
```

**Comment by linonetwo** [comment]
Yse I can log it out:

```js
  const [vt] = useVT(
    () => ({
      scroll: { y: height },
      onScroll: ({ top }) => {
        console.log(top);
      },
    }),
    [],
  );
```

but helplessly I can't controll it...

**Comment by wubostc** [comment]
> Yse I can log it out:
> 
> ```js
>   const [vt] = useVT(
>     () => ({
>       scroll: { y: height },
>       onScroll: ({ top }) => {
>         console.log(top);
>       },
>     }),
>     [],
>   );
> ```
> 
> but helplessly I can't controll it...

Yep, there's no way to control... o(╥﹏╥)o
