### ISSUE TITLE
Error with v1.1.1

### ISSUE THREAD

**Issue by Vincz** [wubostc/virtualized-table-for-antd#82]
With v1.1.1 I started to get the following error: `rows.slice is not a function`
At this line : https://github.com/wubostc/virtualized-table-for-antd/blob/eb92d8dd49b48d70edba326c74d992f24979d262/src/vt.tsx#L685
It seems to be when my datasource is empty (while it is loading from server)

No problem with v1.1.0

Any idea ?

Thanks!

**Comment by wubostc** [comment]
resolved in v1.1.2!
