### ISSUE TITLE
Height not resume after clear the content

### ISSUE THREAD

**Issue by linonetwo** [wubostc/virtualized-table-for-antd#83]
<img width="1681" alt="截屏2020-11-19 下午6 46 55" src="https://user-images.githubusercontent.com/3746270/99656364-bdf04300-2a97-11eb-9479-8e7880ed025a.png">

It is huge, and later I make the data source a `[]`, but the container's height is not resuming to 0.

**Comment by wubostc** [comment]
兄弟，你更新一下版本就好了

**Comment by linonetwo** [comment]
可以了，腰不酸腿不疼了
