### ISSUE TITLE
最新的版本好像不支持antd3了，请问支持antd3的版本还继续维护吗

### ISSUE THREAD

**Issue by zhongtingbing** [wubostc/virtualized-table-for-antd#86]

**Comment by wubostc** [comment]
没bug就不更新了

**Comment by zhongtingbing** [comment]
好的，有没有考虑过表格中带子表格的情况，如：
![image](https://user-images.githubusercontent.com/22792830/102996494-30a08280-455e-11eb-8d16-df93262cf0f2.png)这类xin型的表格，当滚动时，会出现大片空白的情况如下图所示

**Comment by zhongtingbing** [comment]
好的，当表格中带子表格的情况，如：
![image](https://user-images.githubusercontent.com/22792830/102996767-9d1b8180-455e-11eb-9406-3de90c226b53.png)
时，滚动列表会出先大片空白，如下图所示：
![image](https://user-images.githubusercontent.com/22792830/102996928-e9ff5800-455e-11eb-9c1c-11b9996f5a88.png)

这种情况可以支持下吗

**Comment by zhongtingbing** [comment]
OK，在antd3中，如果数据源（dataSource）中的数据含有children字端（即表格的行嵌套），会出先schroll.y动态变化的情况，造成试图上大量留白甚至看不到图标，这种情况大佬能不能考虑兼容下。

**Comment by zhongtingbing** [comment]
如数据格式：  useEffect(() => {
    const a = [];
    for (let i = 0; i < 1000; i++) {
      a.push({
        name: 'ww',
        id: i,
        index: i + 1,
        children: [
          {
            name: 'ww',
            id: guid(),
          },
          {
            name: 'ww',
            id: guid(),
          },
          {
            name: 'ww',
            id: guid(),
          },
        ],
      });
    }
    setRows(a);
  }, []);

**Comment by zhongtingbing** [comment]
![Uploading image.png…]()
