### ISSUE TITLE
Reference of VT undefined

### ISSUE THREAD

**Issue by dcfranca** [wubostc/virtualized-table-for-antd#87]
Hi,
I was trying to achieve a simple scroll to using Antd + visualized-table-for-antd
First, I was doing a workaround of removing the virtualized components when I had to scroll on an element not visible on the screen, but then I realized that `virtualized-table-for-antd` might have the feature I need.

But I can't make it work with my current code.
I'm using Antd3, not sure if this might be the reason, but I was following the example code from [here](https://github.com/wubostc/virtualized-table-for-antd/blob/master/test/scroll-to.tsx)

So my minimum partial code is the following:

```javascript
import React, { useRef } from 'react';
import { useVT } from 'virtualizedtableforantd';

import { Table, Button } from 'antd';

const MyComponent = () => {
  const gridRef = useRef();
  const [forceFocus, setForceFocus] = useState(false);
  const [VT] = useVT(() => {
      return {
        scroll: { y: 600 },
        initTop: 1000,
        debug: true,
        ref: gridRef
      }}, []);

     return (<div>
          <Button
              onClick={() => {
                gridRef.current.scrollTo(-1)
              }}
            >
              Jump to End
            </Button>
  
           <Table
              components={VT}
              bordered
              scroll={{ y: '60vh' }}
              dataSource={myData}
              columns={myColumns}
              style={{ width: '112%' }}
              rowClassName="editable-row"
              pagination={false}
          />
    </div>);
}

```

However, every time I click on the button to jump to the bottom I get an error:

> TypeError: gridRef.current is undefined

As the reference is not being correctly assigned, am I missing something? Is there anything else I have to do in order to assign it properly?

**Comment by wubostc** [comment]
hi guys
only   ```virtualizedtableforantd**4**``` supports  this usage:  ref.current.scrollTo(...)
