### ISSUE TITLE
关于table可展开行现实问题

### ISSUE THREAD

**Issue by zhongtingbing** [wubostc/virtualized-table-for-antd#89]
你好，在antd3中，如果数据源（dataSource）中的数据含有children字段（即表格的行嵌套），滚动时会有大量留白甚至看不到行列，（视图区的渲染item减少了,需手动点击展开才能重新铺满）这种情况大佬能不能考虑兼容下，期待你的回复

**Comment by wubostc** [comment]
这对现有的架构有稳定性和性能影响
很麻烦😅(๑°⌓°๑)
你也可以提个PR

**Comment by zhongtingbing** [comment]
其实也还好，对包含children的列动态取tail的值能够解决。。感谢大佬的代码
