### ISSUE TITLE
Style Error

### ISSUE THREAD

**Issue by Nokecy** [wubostc/virtualized-table-for-antd#9]
因为在Table上套了一层Div 导致原AntTable 有些样式不生效了。比如size  fixed=“right” 等等

**Comment by Nokecy** [comment]
看了antTable的less 都是className > table {} 这样导致table 必须是子元素 ，中间套个div 就不生效了

**Comment by wubostc** [comment]
并不是这个原因，你可以把components去掉看看原来的，fixed设定后，样式的变更发生在顶层DOM上

**Comment by Nokecy** [comment]
![image](https://user-images.githubusercontent.com/12318131/59907930-c8d81b80-943e-11e9-95b7-2196741f822c.png)

![image](https://user-images.githubusercontent.com/12318131/59907976-edcc8e80-943e-11e9-92c0-6e8350b9de0e.png)

**Comment by Nokecy** [comment]
麻烦看下图一和图二的对比 ，中间套了个div导致样式没有应用上。。。。

**Comment by wubostc** [comment]
README.md有写：maybe you need to fix your style
你可以自己加啊-=

**Comment by Nokecy** [comment]
~~~~

**Comment by Nokecy** [comment]
明白了 ，可以在那个套的div上加个className 吗 例如 vt-table

**Comment by wubostc** [comment]
具体怎么弄？

**Comment by Nokecy** [comment]
把ant-table的less 文件拷过来 改 在必要位置加上 那个套的div的class
![image](https://user-images.githubusercontent.com/12318131/59911154-dd6be200-9445-11e9-8028-e039db439bc7.png)

**Comment by Nokecy** [comment]
现在还有一个问题 当fixed=‘right’ 时 主table和right table 中间会有一个滚动条的空白，这个修复有思路吗？
![image](https://user-images.githubusercontent.com/12318131/59911319-320f5d00-9446-11e9-8d80-7f1f93e51300.png)

**Comment by wubostc** [comment]
顶层样式的问题，你可以去掉vt看看和原来有什么区别

**Comment by wubostc** [comment]
目前不太好解决，

**Comment by Nokecy** [comment]
去掉就正常了。。。。

**Comment by wubostc** [comment]
less整个文件复制过来是不是处理的有问题？

**Comment by Nokecy** [comment]
不是 空白的，去掉自定义的less一样有 ，因为vt-table 那个div的宽度和父级不一样 ，父级有一个滚动条。

**Comment by Nokecy** [comment]
https://codesandbox.io/embed/crazy-kilby-2l9i1 @wubostc

**Comment by wubostc** [comment]
你得把scroll的x也要加上去，不然样式就有问题，还有col2字段也要赋值-=

**Comment by wubostc** [comment]
新版本提交了
@Nokecy
