### ISSUE TITLE
Expandable rows and tree data support

### ISSUE THREAD

**Issue by bezsinnyidmytro** [wubostc/virtualized-table-for-antd#98]
I do understand it is quite complex but is there any way to support expandable rows and / or tree structures for this virtualised implementation (those are natively supported by ant-d-4 Table at the moment)?
Scroll goes insane after some expanded rows change their height. Degree of "insanity' depends on height difference between collapsed-expanded row state.

It might happen that tree data is not possible to support due to internal implementation of grouping for ant-d Table. 

Will appreciate any insights on this.

p.s. Many thanks for this beautiful package

**Comment by mathmarqq** [comment]
@bezsinnyidmytro maybe this will help https://github.com/wubostc/virtualized-table-for-antd/pull/106

**Comment by wubostc** [comment]
it only supports expandable...
in 1.1.5
